Disable hosting_civicrm before running hostmaster upgrade
Otherwise it bricks hostmaster: Drush command terminated abnormally due to an unrecoverable error.  [error]
Error: Call to undefined function provision_autoload_register_prefix() in
/var/aegir/host_master/006/profiles/hostmaster/modules/aegir/hosting_civicrm/drush/provision_civicrm.drush.inc, line 52